version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-1.8.0-openjdk"

phases:
  install:
    commands:
    - runtime-versions:
    - java: openjdk8
    - echo installing maven...
    - apt-get update -y
    - apt-get install -y maven
  build:
    commands:
    - echo building the justiceleague-tracker
    - mvn test
    - mvn install
artifacts:
  files:
  - target/*.jar
  - scripts/*.sh
  - appspec.yml
  discard-paths: yes

cache:
  paths:
  - '/root/.m2/**/*'
